//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1718_presences_g27.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_1718_presences_g27.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is already taken !.
        /// </summary>
        public static string Error_CodeAlreadyExist {
            get {
                return ResourceManager.GetString("Error_CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date begin is required.
        /// </summary>
        public static string Error_DatesBegin_Required {
            get {
                return ResourceManager.GetString("Error_DatesBegin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be &gt;= end date.
        /// </summary>
        public static string Error_DatesBeginMustBeLower {
            get {
                return ResourceManager.GetString("Error_DatesBeginMustBeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be &gt;= finish date.
        /// </summary>
        public static string Error_DatesEndMustBeHigher {
            get {
                return ResourceManager.GetString("Error_DatesEndMustBeHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be &lt;= start time.
        /// </summary>
        public static string Error_EndTimeMustBeHigher {
            get {
                return ResourceManager.GetString("Error_EndTimeMustBeHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be &gt;= end time.
        /// </summary>
        public static string Error_StartTimeMustBeLower {
            get {
                return ResourceManager.GetString("Error_StartTimeMustBeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is required.
        /// </summary>
        public static string Error_Title_Required {
            get {
                return ResourceManager.GetString("Error_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your don&apos;t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudo:.
        /// </summary>
        public static string LoginView_Pseudo {
            get {
                return ResourceManager.GetString("LoginView_Pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string MembersDetailView_Follow {
            get {
                return ResourceManager.GetString("MembersDetailView_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This member is not related to you..
        /// </summary>
        public static string MembersDetailView_NotRelated {
            get {
                return ResourceManager.GetString("MembersDetailView_NotRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is you !.
        /// </summary>
        public static string MembersDetailView_ThisIsYou {
            get {
                return ResourceManager.GetString("MembersDetailView_ThisIsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        public static string MembersDetailView_Unfollow {
            get {
                return ResourceManager.GetString("MembersDetailView_Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are following this member..
        /// </summary>
        public static string MembersDetailView_YouAreFollowing {
            get {
                return ResourceManager.GetString("MembersDetailView_YouAreFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add student.
        /// </summary>
        public static string Menu_add_Student {
            get {
                return ResourceManager.GetString("Menu_add_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Changes.
        /// </summary>
        public static string Menu_Cancel_Changes {
            get {
                return ResourceManager.GetString("Menu_Cancel_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Menu_Save_Changes {
            get {
                return ResourceManager.GetString("Menu_Save_Changes", resourceCulture);
            }
        }
    }
}
