//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1718_presences_g27
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Courseoccurrence = new HashSet<Courseoccurrence>();
            this.Student = new HashSet<Student>();
        }
    
        public int Code { get; set; }
        public string Title { get; set; }
        public System.TimeSpan Starttime { get; set; }
        public System.TimeSpan Endtime { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime Finishdate { get; set; }
        public int Dayofweek { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courseoccurrence> Courseoccurrence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
